// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  angular.module('fleekApp', []).run(function($rootScope) {
    return $rootScope.root = {};
  });

}).call(this);

//# sourceMappingURL=app.js.map
